export const CLIENTS = [
  {
    src: '/clients/IC_Logo_Dark.svg',
    darkModeSrc: '/clients/IC_Logo_White.svg',
    alt: 'Iconic Collective',
    url: 'https://icollective.agency/',
  },
  {
    src: '/clients/veerah_on_white_bg.png',
    darkModeSrc: '/clients/veerah_on_dark_bg.png',
    alt: 'Veerah',
    url: 'https://www.veerah.com/',
  },
  {
    src: '/clients/IR_on_white_bg.png',
    darkModeSrc: '/clients/IR_on_dark_bg.png',
    alt: 'Intimate Rose',
    url: 'https://www.intimaterose.com/',
  },
  {
    src: '/clients/AC_on_white_bg.png',
    darkModeSrc: '/clients/AC_on_dark_bg.png',
    alt: 'Aged and Charred',
    url: 'https://www.agedandcharred.com/',
  },
  {
    src: '/clients/AC_on_white_bg.png',
    darkModeSrc: '/clients/AC_on_dark_bg.png',
    alt: 'Flowershop by Palazzo Versace',
    url: 'https://flowershop.palazzoversace.ae/',
  },
  {
    src: '/clients/AC_on_white_bg.png',
    darkModeSrc: '/clients/AC_on_dark_bg.png',
    alt: 'Fitcover AU & US',
    url: 'https://fitcover.com/',
  },
  {
    src: '/clients/AC_on_white_bg.png',
    darkModeSrc: '/clients/AC_on_dark_bg.png',
    alt: 'Morning Builder Technologies',
    url: '#',
  },
  {
    src: '/clients/AC_on_white_bg.png',
    darkModeSrc: '/clients/AC_on_dark_bg.png',
    alt: 'HelmX Smart Helmets',
    url: '#',
  },
  {
    src: '/clients/AC_on_white_bg.png',
    darkModeSrc: '/clients/AC_on_dark_bg.png',
    alt: 'Netcare',
    url: 'https://www.netcare.co.za/',
  },
  {
    src: '/clients/AC_on_white_bg.png',
    darkModeSrc: '/clients/AC_on_dark_bg.png',
    alt: 'Plus EV Holdings Inc',
    url: 'https://www.plusevholdings.com/',
  },
  {
    src: '/clients/AC_on_white_bg.png',
    darkModeSrc: '/clients/AC_on_dark_bg.png',
    alt: 'CPUcoin',
    url: 'https://cpucoin.io/',
  },
  {
    src: '/clients/AC_on_white_bg.png',
    darkModeSrc: '/clients/AC_on_dark_bg.png',
    alt: 'Equilibrium',
    url: 'https://equilibrium.com/',
  },
  {
    src: '/clients/AC_on_white_bg.png',
    darkModeSrc: '/clients/AC_on_dark_bg.png',
    alt: 'Tweekit IO',
    url: 'https://tweekit.io/',
  },
  {
    src: '/clients/AC_on_white_bg.png',
    darkModeSrc: '/clients/AC_on_dark_bg.png',
    alt: 'Connexio Cloud',
    url: 'https://www.connexiocloud.com/',
  },
  {
    src: '/clients/AC_on_white_bg.png',
    darkModeSrc: '/clients/AC_on_dark_bg.png',
    alt: 'NGD Systems',
    url: 'https://ngdsystems.com/',
  },
];
